import Footer from "./Footer";
import Header from "./Header";
import React, { ReactNode } from 'react'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import Newsletter from "./Newsletter";



type Props = {
    children: ReactNode
}


export default function Layout( { children }: Props ) {
    return (
      <>
        <Head>
        <title>Ecommerce app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="w-full overflow-x-hidden">
        <Header />
        <main className="w-full">{children}</main>
        <Newsletter />
        <Footer />

        </div>
       
      </>
    )
}
  
